// QueryBuilder: Defining and requesting the recommended paths
export const QUERYBUILDER_FETCH_OPTIONS_TABLE = 'QUERYBUILDER_FETCH_OPTIONS_TABLE'
export const QUERYBUILDER_FETCH_OPTIONS_TABLE_FAILED = 'QUERYBUILDER_FETCH_OPTIONS_TABLE_FAILED'
export const QUERYBUILDER_LOAD_OPTIONS_TABLE = 'QUERYBUILDER_LOAD_OPTIONS_TABLE'
export const QUERYBUILDER_FETCH_PATHS = 'QUERYBUILDER_FETCH_PATHS'
export const QUERYBUILDER_SHOW_PATHS = 'QUERYBUILDER_SHOW_PATHS'
export const QUERYBUILDER_FETCH_PATHS_FAILED = 'QUERYBUILDER_FETCH_PATHS_FAILED'
export const QUERYBUILDER_SELECT_GRADE = 'QUERYBUILDER_SELECT_GRADE'
export const QUERYBUILDER_SELECT_COURSE = 'QUERYBUILDER_SELECT_COURSE'
export const QUERYBUILDER_SELECT_TOPIC = 'QUERYBUILDER_SELECT_TOPIC'
export const QUERYBUILDER_SELECT_SUBJECT = 'QUERYBUILDER_SELECT_SUBJECT'
export const QUERYBUILDER_SELECT_STANDARD = 'QUERYBUILDER_SELECT_STANDARD'

// PathViewer: Rendering and editing the recommended path
export const PATHVIEWER_MOVE_UP_FOCUS_AREA = 'PATHVIEWER_MOVE_UP_FOCUS_AREA'
export const PATHVIEWER_MOVE_DOWN_FOCUS_AREA = 'PATHVIEWER_MOVE_DOWN_FOCUS_AREA'
export const PATHVIEWER_ADD_FOCUS_AREA = 'PATHVIEWER_ADD_FOCUS_AREA'
export const PATHVIEWER_REMOVE_FOCUS_AREA = 'PATHVIEWER_REMOVE_FOCUS_AREA'