// QueryBuilder: Defining and requesting the recommended paths
export const QUERYBUILDER_FETCH_OPTIONS_TABLE = 'QUERYBUILDER_FETCH_OPTIONS_TABLE'
export const QUERYBUILDER_FETCH_OPTIONS_TABLE_FAILED = 'QUERYBUILDER_FETCH_OPTIONS_TABLE_FAILED'
export const QUERYBUILDER_LOAD_OPTIONS_TABLE = 'QUERYBUILDER_LOAD_OPTIONS_TABLE'
export const QUERYBUILDER_SELECT_GRADE = 'QUERYBUILDER_SELECT_GRADE'
export const QUERYBUILDER_SELECT_COURSE = 'QUERYBUILDER_SELECT_COURSE'
export const QUERYBUILDER_SELECT_TOPIC = 'QUERYBUILDER_SELECT_TOPIC'
export const QUERYBUILDER_SELECT_SUBJECT = 'QUERYBUILDER_SELECT_SUBJECT'
export const QUERYBUILDER_SELECT_STANDARD = 'QUERYBUILDER_SELECT_STANDARD'
export const QUERYBUILDER_REMOVE_GRADE = 'QUERYBUILDER_REMOVE_GRADE'
export const QUERYBUILDER_REMOVE_COURSE = 'QUERYBUILDER_REMOVE_COURSE'
export const QUERYBUILDER_REMOVE_TOPIC = 'QUERYBUILDER_REMOVE_TOPIC'
export const QUERYBUILDER_REMOVE_SUBJECT = 'QUERYBUILDER_REMOVE_SUBJECT'
export const QUERYBUILDER_REMOVE_STANDARD = 'QUERYBUILDER_REMOVE_STANDARD'

// Shared: requesting the paths
export const QUERYBUILDER_FETCH_PATHS = 'QUERYBUILDER_FETCH_PATHS'
export const QUERYBUILDER_SHOW_PATHS = 'QUERYBUILDER_SHOW_PATHS'
export const QUERYBUILDER_FETCH_PATHS_FAILED = 'QUERYBUILDER_FETCH_PATHS_FAILED'

// PathViewer: Rendering and editing the recommended path
export const PATHVIEWER_CHANGE_CURRENT_PATH = 'PATHVIEWER_CHANGE_CURRENT_PATH'
export const PATHVIEWER_MOVE_UP_FOCUS_AREA = 'PATHVIEWER_MOVE_UP_FOCUS_AREA'
export const PATHVIEWER_MOVE_DOWN_FOCUS_AREA = 'PATHVIEWER_MOVE_DOWN_FOCUS_AREA'
export const PATHVIEWER_REMOVE_FOCUS_AREA = 'PATHVIEWER_REMOVE_FOCUS_AREA'
export const PATHVIEWER_FETCH_FOCUS_AREA_OPTIONS = 'PATHVIEWER_FETCH_FOCUS_AREA_OPTIONS'
export const PATHVIEWER_LOAD_FOCUS_AREA_OPTIONS = 'PATHVIEWER_LOAD_FOCUS_AREA_OPTIONS'
export const PATHVIEWER_FETCH_FOCUS_AREA_OPTIONS_FAILED = 'PATHVIEWER_FETCH_FOCUS_AREA_OPTIONS_FAILED'
export const PATHVIEWER_ADD_FOCUS_AREA = 'PATHVIEWER_ADD_FOCUS_AREA'

// Pathviewer: Detail drawers
export const REQUEST_FOCUS_AREA_INFO = 'REQUEST_FOCUS_AREA_INFO'
export const SUCCESS_FOCUS_AREA_INFO = 'SUCCESS_FOCUS_AREA_INFO'
export const ERROR_FOCUS_AREA_INFO = 'ERROR_FOCUS_AREA_INFO'
export const REQUEST_PATH_RELATED_PROJECTS = 'REQUEST_PATH_RELATED_PROJECTS'
export const SUCCESS_PATH_RELATED_PROJECTS = 'SUCCESS_PATH_RELATED_PROJECTS'
export const ERROR_PATH_RELATED_PROJECTS = 'ERROR_PATH_RELATED_PROJECTS'
export const PATHVIEWER_CLEAR_DETAILS = 'PATHVIEWER_CLEAR_DETAILS'


//LIKE / DISLKE
export const REQUEST_RECOMMENDATION = 'REQUEST_RECOMMENDATION'
