export const REQUEST_LOAD_TEACHERS_AND_ADMINS = 'REQUEST_LOAD_TEACHERS_AND_ADMINS';
export const SUCCESS_LOAD_TEACHERS_AND_ADMINS = 'SUCCESS_LOAD_TEACHERS_AND_ADMINS';
export const ERROR_LOAD_TEACHERS_AND_ADMINS = 'ERROR_LOAD_TEACHERS_AND_ADMINS';
export const REQUEST_CHANGE_ROLE = 'REQUEST_CHANGE_ROLE';
export const SUCCESS_CHANGE_ROLE = 'SUCCESS_CHANGE_ROLE';
export const ERROR_CHANGE_ROLE = 'ERROR_CHANGE_ROLE';
